import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import '@/app/globals.css'
import { NftProvider } from '@/Context/NftCardContext'

const urbanist = Urbanist({ subsets: ['latin', 'latin-ext'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <NftProvider>
                <main>
                    <div className="header explore">
                        <div className='page-title-area'>
                            <h1 className='page-title'>Explore</h1>
                            <div className='flex flex-row items-center gap-3'>
                                <h5 className='text-white__second'>Home /</h5>
                                <h5 className='text-white__second'>Explore</h5>
                                <h5>Explore-1</h5>
                            </div>
                        </div>
                    </div>
                    <div className="main-container">
                        {children}
                    </div>
                </main>
            </NftProvider>

        </>

    )
}
