import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/Components/Header/Navbar/page'
import Footer from '@/Components/Footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html style={{ color: "white" }} lang="en">
      <body >
        <main>
          <div className='navbar-container'>
            <div className='container'>
              <Navbar />
            </div>
          </div>
          <div className="container">
            {children}
          </div>
        </main>

        <footer>
          <Footer />
        </footer>
      </body>

    </html>
  )
}
