import type { Metadata } from 'next'
import { Urbanist} from 'next/font/google'
import './globals.css'
import Navbar from '@/Components/Header/Navbar/page'
import Footer from '@/Components/Footer/page'
import { NftProvider } from '@/Context/NftCardContext'

const urbanist = Urbanist( {subsets: ['latin', 'latin-ext']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html style={{ color: "white" }} className={urbanist.className} lang="en">
      <body >
        <NftProvider>
          <main>
            
            <div className='navbar-container'>
              <div className='main-container'>
                <Navbar />
              </div>
            </div>
            <div className="main-container">

              {children}


            </div>
          </main>

          <footer>
            <Footer />
          </footer></NftProvider>
      </body>

    </html>
  )
}
